---
# This workflow integrates ShiftLeft Ocular with GitHub
# Visit https://docs.shiftleft.io for help
name: Ocular

on:
  pull_request:
  workflow_dispatch:

jobs:
  Ocular-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Ocular scan
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/reports
        ${GITHUB_WORKSPACE}/sl auth --no-diagnostic
        ${GITHUB_WORKSPACE}/sl ocular -- -J-Xmx7G --script oc_scripts/scan.sc --params payload=${GITHUB_WORKSPACE},payloadType=JS,resultFile=${GITHUB_WORKSPACE}/reports/findings.md,graphsDir=${GITHUB_WORKSPACE}/reports
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ocular-scan-reports
        path: reports
